openapi: '3.0.3'
info:
  title: 'clients-info'
  version: '1.1.1'
servers:
  - url: local
paths:
  /client/{clientId}:
    parameters:
    - name: clientId
      in: path
      required: true
      schema:
        type: string
    get:
      description: получение обогащенных данных клиента по Id
      operationId: getClientData
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/dummy'

components:
  schemas:
    dummy:
      type: object

